#pragma once
#include <ThemidaSDK\ThemidaSDK.h>
#include <Windows.h>
#include <string>
#include <vector>
#include <Shlobj.h>
#include <xstring>
#include <ctime>
#include <iostream>
#include <sys/timeb.h>
#include <stdint.h>
#include "ImGuiHeader.h"
#include "Logger.h"
#include "Value.h"
#include "FloatValue.h"
#include "BooleanValue.h"
#include "ModeValue.h"
#include "InlineHook.h"
#include "Forwards.hpp"
